version: 0.2

env:
  variables:
    DOCKER_IMAGE_TAG: ""
    APP_NAME: "python-server"
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /py-app/docker-credentials/DOCKER_REGISTRY_USERNAME
    DOCKER_REGISTRY_PASSWORD: /py-app/docker-credentials/DOCKER_REGISTRY_PASSWORD
    DOCKER_REGISTRY_URL: /py-app/docker-registry/DOCKER_REGISTRY_URL
phases:
  install:
    runtime-version:
      python: 3.11
    pre_build:
      commands:
        - pip install -r app/requirements.txt
    build:
      commands:
        - cd app/
        - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
        - DOCKER_IMAGE_ID=$(docker build -t $APP_NAME .)
        - DOCKER_IMAGE_TAG=${DOCKER_IMAGE_ID: -5}
        - docker tag $APP_NAME "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/$APP_NAME:$DOCKER_IMAGE_TAG"
        - echo "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/$APP_NAME:$DOCKER_IMAGE_TAG"
    post_build:
      commands:
        - docker push "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/$APP_NAME:$DOCKER_IMAGE_TAG"
artifacts:
  files:
    - "**/*"
  base-directory: ../app
