version: 0.2

env:
  variables:
    DOCKER_IMAGE_TAG: ""
    APP_NAME: "python-server"
  parameter-store:
    DOCKER_REGISTRY_USERNAME: /py-app/docker-credentials/DOCKER_REGISTRY_USERNAME
    DOCKER_REGISTRY_PASSWORD: /py-app/docker-credentials/DOCKER_REGISTRY_PASSWORD
    DOCKER_REGISTRY_URL: /py-app/docker-registry/DOCKER_REGISTRY_URL
phases:
  install:
    runtime-version:
      python: 3.11
  pre_build:
    commands:
      - pip install -r app/requirements.txt
  build:
    commands:
      - cd app/
      - echo "$DOCKER_REGISTRY_PASSWORD" | docker login -u "$DOCKER_REGISTRY_USERNAME" --password-stdin "$DOCKER_REGISTRY_URL"
      - docker build -t "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/$APP_NAME:latest" .
      - echo "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/$APP_NAME:latest"
  post_build:
    commands:
      - docker push "$DOCKER_REGISTRY_URL/$DOCKER_REGISTRY_USERNAME/$APP_NAME:latest"
artifacts:
  files:
    - "**/*"
  base-directory: .
